package com.example.clinic_Appointment_Queue_Management_System.enumaration;

public enum Specialization {
    GENERAL_PHYSICIAN,
    CARDIOLOGIST,
    DERMATOLOGIST,
    PEDIATRICIAN,
    NEUROLOGIST,
    ORTHOPEDIC_SURGEON,
    GYNECOLOGIST,
    OPHTHALMOLOGIST,
    PSYCHIATRIST,
    UROLOGIST,
    ONCOLOGIST,
    ENDOCRINOLOGIST,
    GASTROENTEROLOGIST,
    PULMONOLOGIST,
    NEPHROLOGIST,
    RADIOLOGIST,
    ANESTHESIOLOGIST,
    ENT_SPECIALIST,
    DENTIST,
    PHYSIOTHERAPIST
}
